=== Narendra725/Power_BI_Spark_Labs/Power BI/Automations/Power Bi Desktop/Mach3/schemas_cache/schema.json
{"$id": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/report/3.0.0/schema.json", "$schema": "http://json-schema.org/draft-07/schema#", "title": "Report", "description": "Defines a report and its pages, visuals, settings, and additional information.", "type": "object", "properties": {"$schema": {"description": "Defines the schema to use for an item.", "type": "string", "const": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/report/3.0.0/schema.json"}, "themeCollection": {"$ref": "#/definitions/ThemeCollection", "description": "Define a theme (built-in and/or a custom theme) to be used for this report."}, "filterConfig": {"description": "Filters that apply to the entire report (all pages and all visuals).", "$ref": "../../filterConfiguration/1.2.0/schema-embedded.json"}, "objects": {"description": "Specifies the formatting to be set for different \"objects\" of a report.", "$ref": "#/definitions/ReportFormattingObjects"}, "reportSource": {"description": "Defines how the report was created.", "type": "string", "anyOf": [{"const": "Default", "description": "A blank report generated by Power BI apps."}, {"const": "SharePoint", "description": "A quick create report created from a SharePointList."}, {"const": "Teams", "description": "A quick create report created from Teams."}, {"const": "QuickCreate", "description": "A quick create report created from Power BI app."}, {"const": "EmbedQuickCreate", "description": "A quick create report created from an embedded source."}, {"const": "Datamart", "description": "A new report created from Datamart."}, {"const": "DataExplore", "description": "A report generated by exporting an Exploration as a report."}]}, "publicCustomVisuals": {"description": "Names of the custom visuals used in this report from AppSource.", "type": "array", "items": {"type": "string"}}, "resourcePackages": {"description": "Set of resources used within this report.", "type": "array", "items": {"$ref": "#/definitions/ResourcePackage"}}, "organizationCustomVisuals": {"description": "Names and metadata of the organization approved custom visuals used in the report.", "type": "array", "items": {"$ref": "#/definitions/OrganizationCustomVisual"}}, "annotations": {"description": "Additional information to be saved (for example comments, readme, etc) for this report.", "type": "array", "items": {"$ref": "#/definitions/Annotation"}}, "dataSourceVariables": {"description": "A string containing the state of any variables from the underlying direct query data source that should be overridden when rendering this content.\nData source variables do not supply values for M parameters in the semantic model. Instead, data source variables are applied when accessing the underlying direct query source.", "type": "string"}, "settings": {"description": "Settings for the report.", "$ref": "#/definitions/ExplorationSettings"}, "slowDataSourceSettings": {"description": "Settings for slow data sources (for example turning all apply all button for filters).", "$ref": "#/definitions/ExplorationSlowDataSourceSettings"}}, "additionalProperties": false, "required": ["$schema", "themeCollection"], "definitions": {"ThemeCollection": {"type": "object", "properties": {"baseTheme": {"description": "Defines the base monthly release themes shipped with Power BI.", "$ref": "#/definitions/ThemeMetadata"}, "customTheme": {"description": "Defines a custom theme that is applied on top of the base theme.\nProperties not defined in the custom theme will fallback to using the base theme.", "$ref": "#/definitions/ThemeMetadata"}}, "additionalProperties": false}, "ThemeMetadata": {"type": "object", "properties": {"name": {"description": "Name of the theme.", "type": "string"}, "reportVersionAtImport": {"$ref": "#/definitions/ThemeVersion", "description": "Versions when the theme was added to the report."}, "type": {"$ref": "#/definitions/ThemeResourcePackageType", "description": "Built-in or user specific custom theme."}}, "additionalProperties": false, "required": ["name", "reportVersionAtImport", "type"]}, "ThemeVersion": {"type": "object", "properties": {"visual": {"description": "The max visual container version at import.", "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$", "type": "string"}, "page": {"description": "The max page version at import.", "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$", "type": "string"}, "report": {"description": "The max report version at import.", "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$", "type": "string"}}, "additionalProperties": false, "required": ["page", "report", "visual"]}, "ThemeResourcePackageType": {"type": "string", "anyOf": [{"const": "RegisteredResources", "description": "Additional resources not bundled as part of the Power BI application."}, {"const": "SharedResources", "description": "Resources bundled as part of the Power BI applications."}]}, "ReportFormattingObjects": {"type": "object", "properties": {"outspacePane": {"type": "array", "items": {"type": "object", "properties": {"selector": {"description": "Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.", "$ref": "../../formattingObjectDefinitions/1.4.0/schema.json#/definitions/Selector"}, "properties": {"$ref": "#/definitions/OutspacePane", "description": "Describes the properties of the object to apply formatting changes to."}}, "additionalProperties": false, "required": ["properties"]}}, "section": {"type": "array", "items": {"type": "object", "properties": {"selector": {"description": "Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.", "$ref": "../../formattingObjectDefinitions/1.4.0/schema.json#/definitions/Selector"}, "properties": {"$ref": "#/definitions/Section", "description": "Describes the properties of the object to apply formatting changes to."}}, "additionalProperties": false, "required": ["properties"]}}}, "additionalProperties": false}, "OutspacePane": {"type": "object", "properties": {"expanded": {}, "visible": {}}, "additionalProperties": false}, "Section": {"type": "object", "properties": {"verticalAlignment": {}}, "additionalProperties": false}, "ResourcePackage": {"type": "object", "properties": {"id": {"type": "number"}, "name": {"type": "string"}, "type": {"$ref": "#/definitions/ResourcePackageType"}, "items": {"type": "array", "items": {"$ref": "#/definitions/ResourcePackageItem"}}, "disabled": {"type": "boolean"}}, "additionalProperties": false, "required": ["items", "name", "type"]}, "ResourcePackageType": {"type": "string", "anyOf": [{"const": "CustomVisual"}, {"const": "RegisteredResources"}, {"const": "SharedResources"}, {"const": "OrganizationalStoreCustomVisual"}]}, "ResourcePackageItem": {"type": "object", "properties": {"id": {"type": "number"}, "name": {"type": "string"}, "path": {"type": "string"}, "type": {"$ref": "#/definitions/ResourcePackageItemType"}}, "additionalProperties": false, "required": ["name", "path", "type"]}, "ResourcePackageItemType": {"type": "string", "anyOf": [{"const": "CustomVisualJavascript"}, {"const": "CustomVisualsCss"}, {"const": "CustomVisualScreenshot"}, {"const": "CustomVisualIcon"}, {"const": "CustomVisualWatermark"}, {"const": "CustomVisualMetadata"}, {"const": "Image"}, {"const": "ShapeMap"}, {"const": "CustomTheme"}, {"const": "BaseTheme"}, {"const": "DashboardTheme"}, {"const": "DashboardBaseTheme"}, {"const": "HighContrastTheme"}, {"const": "AppNavigation"}, {"const": "AppTheme"}, {"const": "AppBaseTheme"}]}, "OrganizationCustomVisual": {"type": "object", "properties": {"name": {"description": "Name of the organization custom visual.", "type": "string"}, "path": {"description": "Path where the custom visual is stored.", "type": "string"}, "disabled": {"description": "Signifies if the custom visual is disabled by the organization.", "type": "boolean"}}, "additionalProperties": false, "required": ["name", "path"]}, "Annotation": {"type": "object", "properties": {"name": {"description": "Unique name for the annotation.", "type": "string"}, "value": {"description": "A value for this annotation.", "type": "string"}}, "additionalProperties": false, "required": ["name", "value"]}, "ExplorationSettings": {"type": "object", "properties": {"isPersistentUserStateDisabled": {"description": "Disable saving state of changes to a report as report viewers modify slicers and filters.", "type": "boolean"}, "hideVisualContainerHeader": {"description": "Hide visual container header in view mode of the report.", "type": "boolean"}, "useStylableVisualContainerHeader": {"description": "Use the new visual container header that is formattable.", "type": "boolean"}, "exportDataMode": {"description": "When exporting data, what should be exported.", "type": "string", "anyOf": [{"const": "AllowSummarized", "description": "Only allow summarized data."}, {"const": "AllowSummarizedAndUnderlying", "description": "Allow underlying and summarized data."}, {"const": "None", "description": "Don't allow exporting data."}]}, "isReportAnnotationsDisabled": {"description": "Commenting is disabled for this report.", "type": "boolean"}, "defaultFilterActionIsDataFilter": {"description": "When selecting data points on a visual, it will result in apply that selection as a filter instead of a highlight on other visuals.", "type": "boolean"}, "defaultDrillFilterOtherVisuals": {"description": "When another visual is drilled, if visual interactions are enabled between the two visuals, then this property specifies if that drill should be applied as a filter to this visual.\nCan be overridden by setting on individual visuals.", "type": "boolean"}, "useCrossReportDrillthrough": {"description": "Allow drill-through from other reports to this report.", "type": "boolean"}, "allowChangeFilterTypes": {"description": "Disables changing the type of filter in view mode.", "type": "boolean"}, "allowInlineExploration": {"description": "Allows personalize this visual for the report in view mode.", "type": "boolean"}, "useEnhancedTooltips": {"description": "Uses better tooltips for the visuals in this report.", "type": "boolean"}, "useScaledTooltips": {"description": "If enabled, the tooltip will scale to match canvas zoom.", "type": "boolean"}, "filterPaneHiddenInEditMode": {"description": "Hide the filter pane in view mode.", "type": "boolean"}, "disableFilterPaneSearch": {"description": "Disables the search bar in filter pane.", "type": "boolean"}, "pagesPosition": {"description": "Default location where the page navigator is shown.", "type": "string", "anyOf": [{"const": "PagesPane", "description": "In a pane next to the report."}, {"const": "Bottom", "description": "In a toolbar below the report."}]}, "allowAutomatedInsightsNotification": {"description": "Allow generating insights for the report in the background on data refresh.", "type": "boolean"}, "useDefaultAggregateDisplayName": {"description": "Show the default aggregate in display names for summarized data.", "type": "boolean"}, "enableDeveloperMode": {"description": "Enables developer mode for testing private custom visuals.", "type": "boolean"}, "pauseQueries": {"description": "Allows pausing queries while making changes to a visual, so every change doesn't trigger a query.\nParticularly useful with slow data sources.", "type": "boolean"}, "queryLimitOption": {"description": "Describes the limitations for how long and how much compute a single query can be allowed to consume.\nMore details for different options: https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-set-visual-query-limits", "type": "string", "anyOf": [{"const": "None"}, {"const": "Shared"}, {"const": "Premium"}, {"const": "SQLServerAS"}, {"const": "AzureAS"}, {"const": "Custom"}, {"const": "Auto"}]}, "customMemoryLimit": {"description": "If custom query limit is applied, this value defines the memory limit.", "type": "string"}, "customTimeoutLimit": {"description": "If custom query limit is applied, this value defines the timeout limit.", "type": "string"}}, "additionalProperties": false}, "ExplorationSlowDataSourceSettings": {"type": "object", "properties": {"isCrossHighlightingDisabled": {"description": "Disable cross highlights.", "type": "boolean"}, "isSlicerSelectionsButtonEnabled": {"description": "Adds 'apply' button to slicers.", "type": "boolean"}, "isFilterSelectionsButtonEnabled": {"description": "Adds 'apply' button to filters.", "type": "boolean"}, "isFieldWellButtonEnabled": {"description": "Adds 'apply' button to field changes.", "type": "boolean"}, "isApplyAllButtonEnabled": {"description": "Adds an apply all button.", "type": "boolean"}}, "additionalProperties": false}}}

=== Narendra725/Power_BI_Spark_Labs/Power BI/Automations/Power Bi Desktop/Mach3/programmatic_chapters_definition/report.json
{
  "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/report/3.0.0/schema.json",
  "themeCollection": {
    "baseTheme": {
      "name": "CY24SU06",
      "reportVersionAtImport": {
        "visual": "1.8.92",
        "report": "2.0.92",
        "page": "1.3.92"
      },
      "type": "SharedResources"
    },
    "customTheme": {
      "name": "Custom8273953987843872.json",
      "reportVersionAtImport": {
        "visual": "1.8.93",
        "report": "2.0.93",
        "page": "1.3.93"
      },
      "type": "RegisteredResources"
    }
  },
  "filterConfig": {
    "filters": [
      {
        "name": "819f884e4e0916d7de90",
        "ordinal": 0,
        "field": {
          "Column": {
            "Expression": {
              "SourceRef": {
                "Entity": "Date"
              }
            },
            "Property": "Date"
          }
        },
        "type": "RelativeDate",
        "filter": {
          "Version": 2,
          "From": [
            {
              "Name": "d",
              "Entity": "Date",
              "Type": 0
            }
          ],
          "Where": [
            {
              "Condition": {
                "Comparison": {
                  "ComparisonKind": 0,
                  "Left": {
                    "Column": {
                      "Expression": {
                        "SourceRef": {
                          "Source": "d"
                        }
                      },
                      "Property": "Date"
                    }
                  },
                  "Right": {
                    "DateSpan": {
                      "Expression": {
                        "Now": {}
                      },
                      "TimeUnit": 3
                    }
                  }
                }
              }
            }
          ]
        },
        "howCreated": "User"
      },
      {
        "name": "98d872e30db7b1e2c065",
        "ordinal": 1,
        "field": {
          "Column": {
            "Expression": {
              "SourceRef": {
                "Entity": "Date"
              }
            },
            "Property": "Date"
          }
        },
        "type": "Advanced",
        "filter": {
          "Version": 2,
          "From": [
            {
              "Name": "d",
              "Entity": "Date",
              "Type": 0
            }
          ],
          "Where": [
            {
              "Condition": {
                "Comparison": {
                  "ComparisonKind": 2,
                  "Left": {
                    "Column": {
                      "Expression": {
                        "SourceRef": {
                          "Source": "d"
                        }
                      },
                      "Property": "Date"
                    }
                  },
                  "Right": {
                    "DateSpan": {
                      "Expression": {
                        "Literal": {
                          "Value": "datetime'2024-01-01T00:00:00'"
                        }
                      },
                      "TimeUnit": 5
                    }
                  }
                }
              }
            }
          ]
        },
        "howCreated": "User",
        "isHiddenInViewMode": true,
        "isLockedInViewMode": true
      },
      {
        "name": "da42ae80de672da6a0ce",
        "ordinal": 2,
        "field": {
          "Column": {
            "Expression": {
              "SourceRef": {
                "Entity": "Date"
              }
            },
            "Property": "Future Dates Hidden"
          }
        },
        "type": "Categorical",
        "filter": {
          "Version": 2,
          "From": [
            {
              "Name": "d",
              "Entity": "Date",
              "Type": 0
            }
          ],
          "Where": [
            {
              "Condition": {
                "In": {
                  "Expressions": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Source": "d"
                          }
                        },
                        "Property": "Future Dates Hidden"
                      }
                    }
                  ],
                  "Values": [
                    [
                      {
                        "Literal": {
                          "Value": "'True'"
                        }
                      }
                    ]
                  ]
                }
              }
            }
          ]
        },
        "howCreated": "User",
        "isHiddenInViewMode": true,
        "isLockedInViewMode": true
      },
      {
        "name": "118059265cfefacbd6b1",
        "ordinal": 3,
        "field": {
          "Column": {
            "Expression": {
              "SourceRef": {
                "Entity": "Product"
              }
            },
            "Property": "Item Division"
          }
        },
        "type": "Categorical",
        "howCreated": "User"
      },
      {
        "name": "1b1a99265a03748295e7",
        "ordinal": 4,
        "field": {
          "Column": {
            "Expression": {
              "SourceRef": {
                "Entity": "Product"
              }
            },
            "Property": "Item Department"
          }
        },
        "type": "Categorical",
        "howCreated": "User"
      },
      {
        "name": "1c0252f32d60a3b75f11",
        "ordinal": 5,
        "field": {
          "Column": {
            "Expression": {
              "SourceRef": {
                "Entity": "Product"
              }
            },
            "Property": "Item Main Category"
          }
        },
        "type": "Categorical",
        "howCreated": "User"
      }
    ],
    "filterSortOrder": "Custom"
  },
  "objects": {
    "section": [
      {
        "properties": {
          "verticalAlignment": {
            "expr": {
              "Literal": {
                "Value": "'Top'"
              }
            }
          }
        }
      }
    ],
    "outspacePane": [
      {
        "properties": {
          "expanded": {
            "expr": {
              "Literal": {
                "Value": "false"
              }
            }
          }
        }
      }
    ]
  },
  "publicCustomVisuals": [
    "PBI_CV_9272D058_BEA0_476A_B090_A712545F92FA"
  ],
  "resourcePackages": [
    {
      "name": "RegisteredResources",
      "type": "RegisteredResources",
      "items": [
        {
          "name": "Clear_all_slicers14676744101821415.png",
          "path": "Clear_all_slicers14676744101821415.png",
          "type": "Image"
        },
        {
          "name": "Custom8273953987843872.json",
          "path": "Custom8273953987843872.json",
          "type": "CustomTheme"
        },
        {
          "name": "Dark_Filter12239714763250309.png",
          "path": "Dark_Filter12239714763250309.png",
          "type": "Image"
        },
        {
          "name": "Revenue5709653548238078.png",
          "path": "Revenue5709653548238078.png",
          "type": "Image"
        },
        {
          "name": "Transaction25375699078957157.png",
          "path": "Transaction25375699078957157.png",
          "type": "Image"
        },
        {
          "name": "RSP7171207118047747.png",
          "path": "RSP7171207118047747.png",
          "type": "Image"
        },
        {
          "name": "BSV9643992797576042.png",
          "path": "BSV9643992797576042.png",
          "type": "Image"
        },
        {
          "name": "units2546279553007339.png",
          "path": "units2546279553007339.png",
          "type": "Image"
        },
        {
          "name": "Revenue7562269609032337.png",
          "path": "Revenue7562269609032337.png",
          "type": "Image"
        },
        {
          "name": "Transaction204563823809520828.png",
          "path": "Transaction204563823809520828.png",
          "type": "Image"
        },
        {
          "name": "logo_light5175679416783505.png",
          "path": "logo_light5175679416783505.png",
          "type": "Image"
        },
        {
          "name": "OFF_toggle5017825499638412.png",
          "path": "OFF_toggle5017825499638412.png",
          "type": "Image"
        },
        {
          "name": "ON_toggle35209159514765465.png",
          "path": "ON_toggle35209159514765465.png",
          "type": "Image"
        }
      ]
    },
    {
      "name": "SharedResources",
      "type": "SharedResources",
      "items": [
        {
          "name": "CY24SU06",
          "path": "BaseThemes/CY24SU06.json",
          "type": "BaseTheme"
        }
      ]
    }
  ],
  "settings": {
    "isPersistentUserStateDisabled": true,
    "useStylableVisualContainerHeader": true,
    "defaultFilterActionIsDataFilter": true,
    "defaultDrillFilterOtherVisuals": true,
    "allowChangeFilterTypes": true,
    "allowInlineExploration": true,
    "useEnhancedTooltips": true,
    "useDefaultAggregateDisplayName": true,
    "queryLimitOption": "None",
    "customMemoryLimit": "1048576",
    "customTimeoutLimit": "225"
  },
  "slowDataSourceSettings": {
    "isCrossHighlightingDisabled": false,
    "isSlicerSelectionsButtonEnabled": false,
    "isFilterSelectionsButtonEnabled": false,
    "isFieldWellButtonEnabled": false,
    "isApplyAllButtonEnabled": false
  }
}
